version: "3.3"
services:
  app_1:
    environment:
      - APP_ID=APP_1
      - APP_NUM=1
      - PORT=1010
    build:
      context: ./web-backend-consul
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 1010:9090
  app_2:
    environment:
      - APP_ID=APP_2
      - APP_NUM=2
      - PORT=2020
    build:
      context: ./web-backend-consul
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    ports:
      - 2020:9090
  app_3:
    environment:
      - APP_ID=APP_3
      - APP_NUM=3
      - PORT=3030
    build:
      context: ./web-backend-consul
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    ports:
      - 3030:9090
  app_4:
    environment:
      - APP_ID=APP_4
      - APP_NUM=4
      - PORT=4040
    build:
      context: ./web-backend-consul
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - 4040:9090
  app_5:
    environment:
      - APP_ID=APP_5
      - APP_NUM=5
      - PORT=5050
    build:
      context: ./web-backend-consul
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    ports:
      - 5050:9090
  app_6:
    environment:
      - APP_ID=APP_6
      - APP_NUM=6
      - PORT=6060
    build:
      context: ./web-backend-consul
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    ports:
      - 6060:9090
  app_7:
    environment:
      - APP_ID=APP_7
      - APP_NUM=7
      - PORT=7070
    build:
      context: ./web-backend-consul
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9
    ports:
      - 7070:9090
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    environment:
      - PORTS=8500

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
